### ISSUE TITLE
Posts without titles have empty H4 in "Latest Posts" section

### ISSUE THREAD

**Issue by tomaslibal** [unruly/unruly.github.io#3]
If a post has no title in the RSS feed then the post title element #postsContainer h4.media-heading is empty. 

1) Do we want to have a fallback like "Untitled post" or maybe a randomly generated title which could be something funny in such cases? 
2) Alternatively, we could omit the H4 element if the title value is empty

**Comment by jahed** [comment]
We can either use a short version of the content summary in the title or remove it completely.

If we do remove it completely, we'll need to move the author details under the content summary so the "by" prefix makes sense.

Don't think we should put placeholder text as it'll be off-topic and/or not represent the blog post.

Another option is to remove/ignore it so that the structure stays consistent. The current post without a title is more of a note than an article worth listing.

My vote is on removing any posts without a title.

**Comment by tomaslibal** [comment]
> remove any posts without a title.

+1, I second that option

**Comment by jahed** [comment]
Going to close this. We've frozen the "Devblogs" section and plan to remove it entirely as we get more permanent original content and stop feeding in RSS feeds from other blogs.

**Comment by tomaslibal** [comment]
Ok @jahed Good to see the opensource group trying to bring more original content!
